#!/usr/bin/env python3
"""Generate BlockVault data artefacts from the frozen target list (brief section 12).

Input:  tools/target_list.txt  -  the raw section-12 block, one entry per line:
            block chapter rarity section x y z facing
        (lines outside that shape - fences, prose - are ignored.)

Outputs:
    src/main/resources/vault_items.yml   items: mapping of block -> rarity, sorted
    src/main/resources/vault_slots.json  full manifest (entries + leader + seals)
    tools/spawn_frames.mcfunction        one summon per entry, run from schematic origin

frame = sign + (0,1,0)   head = sign + (0,2,0)   (invariant across all entries)
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "main" / "resources"
LIST = ROOT / "tools" / "target_list.txt"

VERSION = "26.2"
DATA_VERSION = 4903
FACING_BYTE = {"north": 2, "south": 3, "west": 4, "east": 5}

LEADER = {"head": [0, 11, 5], "name_sign": [-1, 11, 5],
          "count_sign": [1, 11, 5], "title": [0, 12, 5]}
SEALS = {"2": [0, 8, 1], "3": [0, 18, 1], "4": [0, 28, 1],
         "5": [0, 38, 1], "6": [0, 48, 1]}

RARITIES = {"common", "uncommon", "rare"}
SECTIONS = {"building", "coloured", "functional", "natural", "redstone"}
LINE = re.compile(
    r"^([a-z0-9_]+)\s+(\d+)\s+(common|uncommon|rare)\s+"
    r"(building|coloured|functional|natural|redstone)\s+"
    r"(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(north|south|east|west)\s*$"
)


def parse(path: Path):
    entries = []
    seen = set()
    coords = {}
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("```") or line.startswith("#"):
            continue
        m = LINE.match(line)
        if not m:
            # tolerate the header line "block chapter rarity section x y z facing"
            if line.split()[:2] == ["block", "chapter"]:
                continue
            raise SystemExit(f"{path}:{n}: unparseable entry: {line!r}")
        block, chap, rarity, section, x, y, z, facing = m.groups()
        if block in seen:
            raise SystemExit(f"{path}:{n}: duplicate block {block!r}")
        seen.add(block)
        sx, sy, sz = int(x), int(y), int(z)
        key = (sx, sy, sz)
        if key in coords:
            raise SystemExit(
                f"{path}:{n}: shelf {sx} {sy} {sz} already used by "
                f"{coords[key]!r} - two blocks cannot share a slot")
        coords[key] = block
        entries.append({
            "block": block, "chapter": int(chap), "rarity": rarity,
            "section": section,
            "sign": [sx, sy, sz],
            "frame": [sx, sy + 1, sz],
            "head": [sx, sy + 2, sz],
            "facing": facing,
        })
    return entries


def main():
    if not LIST.exists():
        raise SystemExit(f"missing {LIST} - paste the brief section-12 block into it")
    entries = parse(LIST)

    # vault_items.yml  -  sorted block -> rarity
    items = "\n".join(f"  {e['block']}: {e['rarity']}"
                      for e in sorted(entries, key=lambda e: e["block"]))
    (SRC / "vault_items.yml").write_text(
        "# Generated by tools/gen_artifacts.py - do not hand-edit.\n"
        f"# edition {VERSION}, {len(entries)} blocks\n"
        "items:\n" + items + "\n", encoding="utf-8")

    # vault_slots.json  -  manifest
    manifest = {
        "version": VERSION, "data_version": DATA_VERSION,
        "entries": entries,
        "leader": LEADER, "seals": SEALS,
    }
    (SRC / "vault_slots.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    # spawn_frames.mcfunction
    lines = ["# Generated by tools/gen_artifacts.py - run standing on the schematic origin.",
             f"# {len(entries)} item frames, edition {VERSION}"]
    for e in entries:
        fx, fy, fz = e["frame"]
        b = FACING_BYTE[e["facing"]]
        lines.append(
            f"summon minecraft:item_frame ~{fx} ~{fy} ~{fz} "
            f"{{Facing:{b}b,Fixed:1b,Invulnerable:1b,Silent:1b}}"
        )
    (ROOT / "tools" / "spawn_frames.mcfunction").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")

    # summary
    by_rarity = {r: 0 for r in RARITIES}
    by_section = {s: 0 for s in SECTIONS}
    for e in entries:
        by_rarity[e["rarity"]] += 1
        by_section[e["section"]] += 1
    print(f"{len(entries)} entries")
    print("rarity :", dict(sorted(by_rarity.items())))
    print("section:", dict(sorted(by_section.items())))
    pts = by_rarity["common"] * 1 + by_rarity["uncommon"] * 5 + by_rarity["rare"] * 10
    print("season points:", pts)


if __name__ == "__main__":
    main()
